/**
 * AUTO-GENERATED by scripts/extract-poses.py - do not edit by hand.
 * Re-run:  .venv-tools/bin/python scripts/extract-poses.py
 *
 * Gives the React layer typed, exact geometry for the extracted poses so it
 * never has to guess crop offsets. `POSE_VIEWBOX` is only consumed by the
 * single-sprite fallback, which frames the `idle` region of the whole sheet.
 */


/** True when six individual pose SVGs were extracted. */
export const HAS_SEPARATE_POSES = true;

/** Every extracted pose, in sheet reading order. */
export const EXTRACTED_POSE_NAMES = [
  "idle",
  "wave",
  "thinking",
  "celebrating",
  "encouraging",
  "walk",
] as const;

/** URL of each pose SVG. */
export const POSE_FILES: Record<string, string> = {
  "idle": "/character/poses/pose-idle.svg",
  "wave": "/character/poses/pose-wave.svg",
  "thinking": "/character/poses/pose-thinking.svg",
  "celebrating": "/character/poses/pose-celebrating.svg",
  "encouraging": "/character/poses/pose-encouraging.svg",
  "walk": "/character/poses/pose-walk.svg",
};

/** Whole sheet, used when the poses could not be split. */
export const SPRITE_FILE = "/character/poses/pose-full.svg";

/** viewBox of the framed region inside the full sheet. */
export const SHEET_VIEW_BOX = {
  x: 0,
  y: 0,
  width: 750,
  height: 500,
};

/** viewBox of each emitted pose frame (identical for all poses). */
export const POSE_VIEW_BOX: Record<string, { x: number; y: number; width: number; height: number }> = {
  "idle": { x: 9.72, y: 14.712, width: 150.06, height: 256.36 },
  "wave": { x: 138.22, y: 14.712, width: 150.06, height: 256.36 },
  "thinking": { x: 257.97, y: 14.712, width: 150.06, height: 256.36 },
  "celebrating": { x: 19.97, y: 239.712, width: 150.06, height: 256.36 },
  "encouraging": { x: 148.72, y: 238.712, width: 150.06, height: 256.36 },
  "walk": { x: 262.72, y: 237.212, width: 150.06, height: 256.36 },
};

/** Pose whose region the single-sprite fallback frames. */
export const SPRITE_FOCUS_POSE = "idle";
